### ISSUE TITLE
Datadome does not solve captcha.

### ISSUE THREAD

**Issue by alex4845** [glizzykingdreko/Datadome-GeeTest-Captcha-Solver#2]
Datadom does not solve captcha images. It does not find a template. However, Geetest recognizes and solves captcha perfectly. How can template recognition be improved?

**Comment by glizzykingdreko** [comment]
Hi,

This repository was created solely for educational purposes to learn about image recognition for GeeTest captcha's of Datadome. It only include an initial base for the image recognition and does not provide a complete solution to the challenge in any way.

The repository is not maintained and should be viewed as a study resource only. However, I do offer APIs or custom solutions for solving Datadome challenges and other similar antibots. Feel free to contact me via email or Discord at glizzykingdreko@protonmail.com or @glizzykingdreko.
